
@echo off
echo Adding remote...
git remote remove origin
git remote add origin https://github.com/Chibunnamu/xcrow-escrow.git
echo Adding files...
git add .
echo Committing...
git commit -m "Implement Postmark Email Notification System and Consent Flow"
echo Pushing...
git push -u origin main
